INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Слива красная','весовая',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Арбуз','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Дыня Колхозница','весовая',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Дыня Гулаба','весовая',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Виногорад черный','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Виноград Киш-миш зеленый','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Виногорад зеленый','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Виногорад Тайфи','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Виногорад Ред Глоб','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Виноград красный','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Виноград Киш-миш розовый','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Груша Санта Мария','весовая',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Груша Пакхам','весовая',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Груша Вильямс','весовая',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Груша Конференц','весовая',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Груша Форель','весовая',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Хурма Королек','весовая',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Хурма Свечка','весовая',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Хурма','весовая',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Лимон','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Мандарин','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Лайм','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Грейпфрут','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Апельсин','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Апельсин для сока','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Апельсин отборный','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Помело','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Ананас Импорт','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Киви','весовой',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Авокадо','шт.',1,3,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Кокос','шт.',1,3,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Киви Голд','шт.',1,3,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Айва','весовая',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Яблоко Гольден','весовое',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Яблоко Либерти','весовое',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Яблоко Ред Чиф','весовое',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Яблоко Эконом','весовое',1,3,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Яблоко Айдаред','весовое',1,3,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Яблоко фасованное','весовое',1,3,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Яблоко Симиренко','весовое',1,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Кабачки','весовые',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Баклажаны грунтовые','весовые',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Чеснок','весовой',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Редис','весовой',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Редька Дайкон','весовая',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Репа','весовая',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Имбирь','весовой',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Капуста цветная','весовая',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Капуста белокочанная','весовая',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Капуста краснокачанная','весовая',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Картофель','весовой',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Картофель красный','весовой',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Картофель Эконом','весовой',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Огурец короткоплодный колючий','весовой',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Огурец среднеплодный гладкий','весовой',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Огурец короткоплодный колючий','весовой',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Перец Ласточка','весовой',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Перец красный','весовой',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Лук Эконом','весовой',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Свекла Эконом','весовая',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Морковь Эконом','весовая',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Томат сливовидный','весовой',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Томат','весовой',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Томат розовый','весовой',2,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Стебель сельдерея','пак.',3,4,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Лук зеленый свежий','пак',3,4,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Петрушка свежая','пак',3,4,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Укроп свежий','пак.',3,4,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Кинза свежая','пак',3,4,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Щавель свежий','пак',3,4,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Капуста китайская','весовая',3,1,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Салат листовой Фриллис','пак',3,4,1);
INSERT INTO goods (name,comment,type_goods_id,units_id,is_active) VALUES ('Салат Айсберг','пак',3,4,1);